language: node_js
node_js:
- node

if: tag =~ ^v\d+.\d+.\d+$

cache:
  yarn: true
  directories:
  - node_modules

env:
  global:
  - WWDC_YEAR="WWDC 2018"

script:
- yarn lint
- yarn generate

before_deploy:
- cd dist
- tar cfz ${TRAVIS_BUILD_DIR}/web-form-${TRAVIS_TAG}.tar.gz ./*

deploy:
  provider: releases
  api_key:
    secure: pERAKfdE8fdxOhjgAhjbD4HYJ3Zmc4xLvXobdZt8c+cAIpcRBwaPmWiyI6wbasGlgeMb2QOoa9MG88TeOnZEbCIGyiKShG6OcfZ0mcG4fB1TStt6Ih1nNxDlpnh9nk0LY8TmDtl/ZzsWMfi+43Ui0aKyUfsIiNmh4chqlx+XDWQmRas483X+9RFqaAn9Hy2L6zP4HSILG36MM4gH3/T6sj7nuFxMsAGDNzt9UD1utQmduLxU5SFlMSbRchwXSP+/R89tG2+P6GULn1vN4scIPkWhgHdc2YzDMzZx1gg1xX8kjDxx8HL515qoCR3y6YWKSm7KRYviXgKHHkVK+2d8fiIx/fmMX60C8L0IGQzgW8v8+rpmVi5bY0+PhchpYcyOzUPgT9/U5gMFVBFn908rSwZXkzNBUYGmnfrxqmrRVtBsRfdwH8eN1FNuYebGBjZJnkAstYRn4YaItMlQRQLAuUgRBVgBo8mQ5Jc9nFfPwCQ9k6N5I6PThwF/8+DFgJBVw/lOJjrIaVFE6iI/tmlLrCzGue4ExHDIAnu8pDMUcUSiz1rYk52gyHbBf6TtCtC2X9EU0VmLI21E9VbyAF5cQbGAT8zAeuCQYdc2f0rgn/lqkiL+c/T8y5yj3C19scFDjq0DGEQtEE9ugqmNBUUrYhHIpvDPAHR9HKLjIq78pIw=
  file: ${TRAVIS_BUILD_DIR}/web-form-${TRAVIS_TAG}.tar.gz
  skip_cleanup: true
  on:
    tags: true
